const fs = require("fs");
const { cyan, redBright } = require("cli-color");
// const configRoleReact = require("../../interactions/buttons/contribuer/config.json").blacklist; // Ce fichier n'existe plus, utiliser la configHandler à la racine si besoin
// const { roles } = require("../../api/permanent");

//const fileList = [];
const customIDList = [];

module.exports = (client) => {
    //roleReact();
    let dirs = fs.readdirSync("./interactions/buttons/");
    if (dirs.length === 0) return;
    console.log(cyan.underline("Buttons chargés :"));
    dirs = dirs.filter((file) => !file.includes("."));
    dirs.push("../buttons");
    dirs.forEach((dir) => {
        // Check if the file is not double loaded
        const files = fs.readdirSync(`./interactions/buttons/${dir}/`).filter((file) => file.endsWith(".js"));
        if (files.length === 0) return;
        console.log(cyan.bold(`> ${dir === "../buttons" ? "sans catégorie" : dir} :`));
        files.forEach((file) => {
            //if (fileList.includes(file)) console.log(redBright.bold(`>> Le button ${file} est déjà chargé ou un deuxième fichier button à le même nom dans le dossier ${dir} !`));
            //fileList.push(file);
            const button = require(`../../interactions/buttons/${dir}/${file}`);
            if (button) {
                // Check if the button customID is defined
                if (button.customID === undefined) return console.log(redBright.bold(`>> Le button dans ${file} n'a pas de customID !`));
                // Check if another button don't have the same customID
                if (customIDList.includes(button.customID)) return console.log(redBright.bold(`>> Le button avec comme id ${button.customID} est déjà chargé ou un doublon existe dans le fichier ${file} situé dans le dossier ${dir} !`));
                customIDList.push(button.customID);

                //Si admin et userOnly non défini, on les défini à false :
                if (!button.admin) button.admin = false;
                if (!button.userOnly) button.userOnly = false;

                button.category = dir === "../buttons" ? "sans_categorie" : dir.toLowerCase();
                console.log(cyan(`  > ${button.customID}`));
                if (dir !== "../buttons") button.customID = `${dir}:${button.customID}`;
                client.buttons.set(button.customID, button);
            }
        });
    });
};

//genere les fichiers des buttons (contribuer)
function roleReact() {
    const contribuer = fs.readdirSync("./interactions/buttons/contribuer").filter((file) => file.endsWith(".js")).map((file) => file.replace(".js", ""));
    const listeRoles = Object.keys(roles).filter((role)=> !role.includes("responsable") && !role.includes("referent")).filter((role) => !configRoleReact.includes(role) && !contribuer.includes(role));
    if (listeRoles.length === 0) return;
    console.log(cyan(`>> ${listeRoles.length} roleReact à ajouter :`));
    for (const role of listeRoles) {
        let code = `
//------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        preload.button.js
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
const {roles} = require("../../../api/permanent.js");
const {rolereact} = require("../../../api/role.js");
module.exports = {
    customID: "${role}",
    runInteraction: async (client, interaction) => {
        return rolereact(interaction, roles.${role});
    }
}`;// Role reacte à vue sont code changer il a présent néssaire de passer le role Id et non le nom du role
        fs.writeFileSync(`./interactions/buttons/contribuer/${role}.js`, code);
        console.log(cyan(`- ${role}.js`));
    }
}
